import LocalizedStrings from 'react-localization'

export const Localization = new LocalizedStrings({
  en: {
    EDUCATION: 'EDUCATION',
    EXPERIENCE: 'EXPERIENCE',
    SKILLS: 'SKILLS',
    LANGUAGES: 'LANGUAGES',
    LICENSES: 'LICENSES',
    PORTFOLIO: 'PORTFOLIO',
    CONTACT_ME: 'CONTACT ME',
    ABOUT_ME: 'ABOUT ME',
    PRESENT: 'Present',

    FIRST_NAME: 'Mohammad Sadegh',
    LAST_NAME: 'Panadgoo',
    JOB_TITLE: 'iOS Developer',
    SUMMARY:
      'Experienced Software Engineer with a demonstrated history of working in the Information Technology industry. Skilled in iOS development, Swift, NodeJS, ReactJS, and backend/frontend development. Strong knowledge of software design principles, clean code practices, and industry standards. Committed to delivering high-quality code and creating innovative solutions to enhance user experience and drive business growth. Adept at collaborating with cross-functional teams and staying up-to-date with emerging technologies. Holds a Master of Science in Software Engineering and a Bachelor of Science in Software Engineering.',
    EXPERIENCE_HISTORY: [
      {
        jobTitle: 'Software Engineer',
        companyName: 'Behpardakht Mellat',
        companyWebsite: 'http://behpardakht.com',
        cityName: 'Tehran',
        startDate: 'Oct 2022',
        endDate: 'not yet',
        isPresent: true,
        details: [
          'Developed and implemented robust and scalable NodeJS applications for the backend, ensuring high performance and efficient data processing.',
          'Utilized ReactJS to build dynamic and responsive user interfaces for the frontend, enhancing user experience and engagement.',
          'Contributed to the development of a digital wallet platform, enabling secure transactions and providing intuitive financial management features.',
          'Implemented various value-added services, enhancing the functionality and user satisfaction of multiple projects.',
          'Actively participated in architectural design discussions, promoting code reusability and modularization to enhance maintainability and scalability.',
          'Employed best practices and industry standards to write clean, efficient, and well-documented code.',
          'Investigated and resolved backend/frontend issues, improving system reliability and minimizing downtime.',
          'Stayed up-to-date with emerging technologies and industry trends, actively sharing knowledge and expertise with team members to drive innovation.',
        ],
      },
      {
        jobTitle: 'iOS Developer',
        companyName: 'Behpardakht Mellat',
        companyWebsite: 'http://behpardakht.com',
        cityName: 'Tehran',
        startDate: 'Feb 2019',
        endDate: 'Oct 2022',
        isPresent: false,
        details: [
          `Owning and developing the infrastructure of the company's iOS applications using Swift and SwiftUI.`,
          'Decreasing dependency and application size by developing components instead of third-party libraries.',
          'Improving applications performance and security.',
          'Designing and adding new features and polishing and debugging existing ones.',
          'Developing POP approach beside OOP to follow SOLID principles.',
          'Publishing developed and tested applications on the App Store and other domestic stores.',
        ],
      },
      {
        jobTitle: 'iOS Developer',
        companyName: 'Behsazan Mellat',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'Tehran',
        startDate: 'Dec 2016',
        endDate: 'Feb 2019',
        isPresent: false,
        details: [
          'Built the iOS version of Mellat Mobile Bank app individually, almost from the ground up.',
          'Converted Android (Java) Application code to Swift (Business Logic, and Encryptions).',
          'Created and added new features to the app and also refactored old features.',
        ],
      },
      {
        jobTitle: 'Delphi Developer',
        companyName: 'Behsazan Mellat',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'Tehran',
        startDate: 'Apr 2015',
        endDate: 'Dec 2016',
        isPresent: false,
        details: ['Developed and added new features to the main banking software.', 'Created the core banking stored procedures in TSQL.'],
      },
    ],

    EDUCATION_HISTORY: [
      {
        universityTitle: 'Azad University Central Tehran Branch',
        universityWebsite: 'https://ctb.iau.ir/en',
        degree: 'Master of Science (M.S.)',
        major: 'Software Engineering',
        graduationDate: 'Jan 2018',
        cityName: 'Tehran',
        details: [],
      },
      {
        universityTitle: 'Azad University Shahr-e-Qods Branch',
        universityWebsite: 'https://qods.iau.ir/',
        degree: 'Bachelor of Science (B.S.)',
        major: 'Software Engineering',
        graduationDate: 'Jul 2012',
        cityName: 'Tehran',
        details: [],
      },
    ],
  },
  fa: {
    EDUCATION: 'تحصیلات',
    EXPERIENCE: 'تجربیات',
    SKILLS: 'مهارت‌ها',
    LANGUAGES: 'زبان‌ها',
    LICENSES: 'مدارک',
    PORTFOLIO: 'نمونه کارها',
    CONTACT_ME: 'تماس با من',
    ABOUT_ME: 'درباره من',
    PRESENT: 'تا به حال',

    FIRST_NAME: 'محمد صادق',
    LAST_NAME: 'پنادگو',
    JOB_TITLE: 'توسعه دهنده iOS',
    SUMMARY:
      'مهندس نرم‌افزار با تجربه‌ی عملیات در صنعت فناوری اطلاعات. ماهر در توسعه‌ی iOS، Swift، NodeJS، ReactJS و توسعه‌ی بک‌اند/فرانت‌اند. دانش قوی در زمینه‌ی اصول طراحی نرم‌افزار، شیوه‌های کدنویسی تمیز و استانداردهای صنعتی. پیوسته قصد دارم نرم‌افزار با کیفیت بالا تحویل دهم و راهکارهای نوآورانه برای بهبود تجربه‌ی کاربری و افزایش رشد تجارت ارائه دهم. توانایی همکاری با تیم‌های چند رشته‌ای و بروز بودن با فناوری‌های نوظهور را دارم. مدرک کارشناسی‌ ارشد مهندسی نرم‌افزار و مدرک کارشناسی مهندسی نرم‌افزار را دارم.',
    EXPERIENCE_HISTORY: [
      {
        jobTitle: 'مهندس نرم‌افزار',
        companyName: 'به پرداخت ملت',
        companyWebsite: 'http://behpardakht.com',
        cityName: 'تهران',
        startDate: 'مهر ماه ۱۴۰۱',
        endDate: '',
        isPresent: true,
        details: [
          'روش‌های مستدل و قابل مقیاس برای توسعه و پیاده‌سازی برنامه‌های NodeJS قدرتمند و مقیاس‌پذیر را برای بک‌اند به کار گرفتم و عملکرد بالا و پردازش داده‌ها با کارایی بالا را تأمین کردم.',
          'ReactJS را برای ساخت رابط کاربری پویا و واکنش‌گرا در بخش جلویی به کار بردم، که تجربه و جذابیت کاربر را بهبود داد.',
          'در توسعه یک پلتفرم کیف پول دیجیتال، شرکت کردم و با امکانات مالی شگفت‌انگیز و پرداخت‌های امن، تجربه مالی کاربر را آسان کردم.',
          'به پیاده‌سازی خدمات ارزش افزوده مختلف نیز پرداختم که عملکرد و رضایت کاربر از چندین پروژه را بهبود بخشید.',
          'دربحث‌های طراحی معماری فعالیت فعال داشتم و با تأیید استفاده مجدد از کدها و به‌معماری‌بندی برای بهبود قابلیت نگهداری و قابلیت مقیاس‌پذیری کد کمک کردم.',
          'بهترین شیوه‌ها و استانداردهای صنعت را برای نوشتن کدی تمیز، کارآمد و با مستندات کاربردی به کار گرفتم.',
          'مشکلات بک‌اند / فرانت‌اند را بررسی کردم و آن‌ها را حل کردم تا قابلیت اعتماد سیستم و حداقل ساعت غیرچاپ ممکن باشد.',
          'آخرین تکنولوژی‌ها و روندهای صنعت را دنبال می‌کردم و به اشتراک‌گذاری دانش و تخصص‌های خود با همکاران تیم به منظور تحرک و نوآوری کمک می‌کردم.',
        ],
      },
      {
        jobTitle: 'توسعه دهنده iOS',
        companyName: 'به پرداخت ملت',
        companyWebsite: 'http://behpardakht.com',
        cityName: 'تهران',
        startDate: 'اسفند ماه ۱۳۹۷',
        endDate: 'مهر ماه ۱۴۰۱',
        isPresent: false,
        details: [
          'مالکیت و توسعه زیرساخت برنامه های iOS این شرکت با استفاده از Swift و SwiftUI.',
          'کاهش وابستگی و اندازه برنامه با توسعه مولفه ها به جای کتابخانه های شخص ثالث.',
          'بهبود عملکرد و امنیت برنامه ها.',
          'طراحی و افزودن ویژگی‌های جدید و صیقل دادن و رفع اشکال‌های موجود.',
          'توسعه رویکرد POP در کنار OOP برای پیروی از اصول SOLID.',
          'انتشار برنامه های توسعه یافته و آزمایش شده در اپ استور و سایر فروشگاه های داخلی.',
        ],
      },
      {
        jobTitle: 'توسعه دهنده iOS',
        companyName: 'بهسازان ملت',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'تهران',
        startDate: 'آذر ماه ۱۳۹۵',
        endDate: 'بهمن ماه ۱۳۹۷',
        isPresent: false,
        details: [
          'نسخه iOS برنامه بانک همراه بانک ملت را به صورت جداگانه و تقریباً از پایه ساخته شده است.',
          'تبدیل کد برنامه اندروید (جاوا) به سویفت (منطق تجاری و رمزگذاری).',
          'ایجاد و افزودن ویژگی های جدید به برنامه و همچنین بازسازی ویژگی های قدیمی.',
        ],
      },
      {
        jobTitle: 'توسعه دهنده Delphi',
        companyName: 'بهسازان ملت',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'تهران',
        startDate: 'اردیبهشت ماه ۱۳۹۴',
        endDate: 'آذر ماه ۱۳۹۵',
        isPresent: false,
        details: ['توسعه و افزودن ویژگی های جدید به نرم افزار اصلی بانکداری.', 'رویه های ذخیره شده بانکی اصلی در TSQL را ایجاد کرد.'],
      },
    ],

    EDUCATION_HISTORY: [
      {
        universityTitle: 'دانشگاه آزاد واحد تهران مرکزی',
        universityWebsite: 'https://ctb.iau.ir/fa',
        degree: 'کارشناسی ارشد',
        major: 'مهندسی کامپیوتر گرایش نرم‌افزار',
        graduationDate: 'بهمن ماه ۱۳۹۶',
        cityName: 'تهران',
        details: [],
      },
      {
        universityTitle: 'دانشگاه آزاد واحد شهر قدس',
        universityWebsite: 'https://qods.iau.ir',
        degree: 'کارشناسی',
        major: 'مهندسی کامپیوتر گرایش نرم‌افزار',
        graduationDate: 'تیر ماه ۱۳۹۱',
        cityName: 'تهران',
        details: [],
      },
    ],
  },
})
