import LocalizedStrings from 'react-localization'

export const Localization = new LocalizedStrings({
  en: {
    EDUCATION: 'EDUCATION',
    EXPERIENCE: 'EXPERIENCE',
    SKILLS: 'SKILLS',
    LANGUAGES: 'LANGUAGES',
    LICENSES: 'LICENSES',
    PORTFOLIO: 'PORTFOLIO',
    CONTACT_ME: 'CONTACT ME',
    ABOUT_ME: 'ABOUT ME',
    PRESENT: 'Present',

    FIRST_NAME: 'Mohammad Sadegh',
    LAST_NAME: 'Panadgoo',
    JOB_TITLE: 'iOS Developer',
    SUMMARY:
      'Enthusiastic software developer with over 8 years of professional experience in banking, fintech, and payment services fields, more than 6 years of which are related to iOS development in an agile environment using the Scrum method and deadline-driven work environments. I take pride in creating testable and scalable code and working well in a team or independently.',
    EXPERIENCE_HISTORY: [
      {
        jobTitle: 'iOS Developer',
        companyName: 'Behpardakht Mellat',
        companyWebsite: 'http://behpardakht.com',
        cityName: 'Tehran',
        startDate: 'Feb 2019',
        endDate: 'not yet',
        isPresent: true,
        details: [
          `Owning and developing the infrastructure of the company's iOS applications using Swift and SwiftUI.`,
          'Decreasing dependency and application size by developing components instead of third-party libraries.',
          'Improving applications performance and security.',
          'Designing and adding new features and polishing and debugging existing ones.',
          'Developing POP approach beside OOP to follow SOLID principles.',
          'Publishing developed and tested applications on the App Store and other domestic stores.',
        ],
      },
      {
        jobTitle: 'iOS Developer',
        companyName: 'Behsazan Mellat',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'Tehran',
        startDate: 'Dec 2016',
        endDate: 'Feb 2019',
        isPresent: false,
        details: [
          'Built the iOS version of Mellat Mobile Bank app individually, almost from the ground up.',
          'Converted Android (Java) Application code to Swift (Business Logic, and Encryptions).',
          'Created and added new features to the app and also refactored old features.',
        ],
      },
      {
        jobTitle: 'Delphi Developer',
        companyName: 'Behsazan Mellat',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'Tehran',
        startDate: 'Apr 2015',
        endDate: 'Dec 2016',
        isPresent: false,
        details: [
          'Developed and added new features to the main banking software.',
          'Created the core banking stored procedures in TSQL.',
        ],
      },
    ],
  },
  fa: {
    EDUCATION: 'تحصیلات',
    EXPERIENCE: 'تجربیات',
    SKILLS: 'مهارت‌ها',
    LANGUAGES: 'زبان‌ها',
    LICENSES: 'مدارک',
    PORTFOLIO: 'نمونه کارها',
    CONTACT_ME: 'تماس با من',
    ABOUT_ME: 'درباره من',
    PRESENT: 'تا به حال',

    FIRST_NAME: 'محمد صادق',
    LAST_NAME: 'پنادگو',
    JOB_TITLE: 'توسعه دهنده iOS',
    SUMMARY:
      'توسعه دهنده نرم افزار مشتاق با بیش از 8 سال تجربه حرفه ای در زمینه های بانکداری، فین تک و خدمات پرداخت که بیش از 6 سال آن مربوط به توسعه iOS در محیطی چابک با استفاده از روش اسکرام و محیط های کاری مهلت محور است. من به ایجاد کد قابل آزمایش و مقیاس پذیر و کار خوب در یک تیم یا مستقل افتخار می کنم.',
    EXPERIENCE_HISTORY: [
      {
        jobTitle: 'توسعه دهنده iOS',
        companyName: 'به پرداخت ملت',
        companyWebsite: 'http://behpardakht.com',
        cityName: 'تهران',
        startDate: 'اسفند ماه ۱۳۹۷',
        endDate: '',
        isPresent: true,
        details: [
          'مالکیت و توسعه زیرساخت برنامه های iOS این شرکت با استفاده از Swift و SwiftUI.',
          'کاهش وابستگی و اندازه برنامه با توسعه مولفه ها به جای کتابخانه های شخص ثالث.',
          'بهبود عملکرد و امنیت برنامه ها.',
          'طراحی و افزودن ویژگی‌های جدید و صیقل دادن و رفع اشکال‌های موجود.',
          'توسعه رویکرد POP در کنار OOP برای پیروی از اصول SOLID.',
          'انتشار برنامه های توسعه یافته و آزمایش شده در اپ استور و سایر فروشگاه های داخلی.',
        ],
      },
      {
        jobTitle: 'توسعه دهنده iOS',
        companyName: 'بهسازان ملت',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'تهران',
        startDate: 'آذر ماه ۱۳۹۵',
        endDate: 'بهمن ماه ۱۳۹۷',
        isPresent: false,
        details: [
          'نسخه iOS برنامه بانک همراه بانک ملت را به صورت جداگانه و تقریباً از پایه ساخته شده است.',
          'تبدیل کد برنامه اندروید (جاوا) به سویفت (منطق تجاری و رمزگذاری).',
          'ایجاد و افزودن ویژگی های جدید به برنامه و همچنین بازسازی ویژگی های قدیمی.',
        ],
      },
      {
        jobTitle: 'توسعه دهنده Delphi',
        companyName: 'بهسازان ملت',
        companyWebsite: 'https://www.behsazan.com',
        cityName: 'تهران',
        startDate: 'اردیبهشت ماه ۱۳۹۴',
        endDate: 'آذر ماه ۱۳۹۵',
        isPresent: false,
        details: [
          'توسعه و افزودن ویژگی های جدید به نرم افزار اصلی بانکداری.',
          'رویه های ذخیره شده بانکی اصلی در TSQL را ایجاد کرد.',
        ],
      },
    ],
  },
})
